print("Thank you for using the CJS standard library as your GOTO!")
print("we aim to provide the ut-most update library for creating the best IronJS applications.")
print("This is the environment launcher.")
print("All the libraries you need: algorithm, debug, directory, input, output, filesystem, net utilties, and string utilities are all imported for you!")

include("algo/for")
include("algo/remove")
include("net/client")
include("pipe/buffer")
include("math/def")
include("stdio")
include("stdfile")
include("stdprefix")
include("stringutil")